### ISSUE TITLE
bidi logo 

### ISSUE THREAD

**Issue by gildasius** [tex-xet/bidi#62] opened 2018-01-24 01:40 UTC
## Brief outline of the issue
I'm using XeLaTeX and prefer to see the bidi logo ("Typeset by the bidi package") optional rather than a feature. It presently is typeset on the title page. I'm using the memoir package.
--Gildas Hamel

**Comment by vafa** [comment] 2018-01-24 01:57
This is a duplicate of #60

**Closed by vafa** 2018-01-24 01:57 UTC
Labels: Duplicate, Feature, Invalid, Minor, Question, Wontfix

**Comment by vafa** [comment] 2018-01-27 07:13
I now accept donations to the bidi package. Anyone can donate any amount to the bidi package using [My PayPal.Me](https://www.paypal.me/persiantex).

The donations allow me to spend more time working on the bidi package and make it even better. If you know that some other people may also be interested in donating to the bidi package development, please let them know.

**Comment by vafa** [comment] 2018-01-28 00:59
I have just uploaded version `32.6` of the `bidi` package to CTAN in which the options `logo` and `pdfinfo` are no longer set to `on` by default in the `bidi` package. This should no longer place the text "Typeset by the `bidi` package" at the bottom of the first page and also should not change the metadata of the pdf file.
