### ISSUE TITLE
"Typeset by the bidi package"

### ISSUE THREAD

**Issue by pandey** [tex-xet/bidi#61] opened 2018-01-23 19:04 UTC
My MikTeX installer updated the bidi package to v32.3 (2018-1-21). Now, when I run XeLaTeX on any document that uses bidi, the text "Typeset by the bidi package" appears in the footer of the first page, shoving the page number down into the margin. This occurs only on the first page.

This behavior does not occur in the previous version, and I've been using the previous version of the package extensively. I haven't updated any other packages or modified the document.  There are no options set for the bidi package. 

The culprit seems to be

```
\define@choicekey{bidi.sty}{logo}[\bidi@tempa\bidi@tempb]{on,off}[on]{%
  \ifcase\bidi@tempb\relax
    \AtBeginDocument{\@bidi@inslogo@}%
  \or
    \let\@bidi@logo@\@empty \let\@bidi@inslogo@\@empty
  \fi}

\ExecuteOptionsX{%
    DetectColumn=off,%
    logo=on%
}
```

In ``\ExecuteOptionsX``, the ``logo`` option should be set to 'off' by default. 

After making the above change in `bidi.sty`, the banner disappeared. 

An update to a TeX package should not introduce new 'features' by default!

**Comment by vafa** [comment] 2018-01-24 01:17
This is a duplicate of #60

**Closed by vafa** 2018-01-24 01:17 UTC
Labels: Duplicate, Feature, Invalid, Minor, Question, Wontfix

**Comment by vafa** [comment] 2018-01-27 07:09
I now accept donations to the bidi package. Anyone can donate any amount to the bidi package using [My PayPal.Me](https://www.paypal.me/persiantex).

The donations allow me to spend more time working on the bidi package and make it even better. If you know that some other people may also be interested in donating to the bidi package development, please let them know.
